version: '3'
services:
  api:
    image: mywebapp
    build: .
#    networks:
#      - backend
    ports:
      - "3000:3000"
#    volumes: 
#      - ./:/usr/src/app

  web-cli:
    image: mywebapp
#    networks:
#      - backend
    command: sh
#    links: 
#      - mongo
  
#  mongo:
#    image: mongo
#    ports: 
#      - "27017:27017"

# networks:
#   backend:
#     driver: bridge